/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConsumptionItem = IDL.Record({
  'month' : IDL.Nat8,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'year' : IDL.Nat16,
  'itemCode' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
  'department' : IDL.Text,
});
export const SavedRow = IDL.Record({
  'qty' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'itemCode' : IDL.Text,
  'department' : IDL.Text,
});
export const SavedEntry = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'rows' : IDL.Vec(SavedRow),
  'savedAt' : IDL.Text,
  'savedBy' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func([ConsumptionItem], [], []),
  'bulkImport' : IDL.Func([IDL.Vec(ConsumptionItem)], [], []),
  'deleteAllEntries' : IDL.Func([], [], []),
  'deleteEntry' : IDL.Func([IDL.Text], [], []),
  'deleteItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(SavedEntry)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(ConsumptionItem)], ['query']),
  'getItemsByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsumptionItem)],
      ['query'],
    ),
  'getItemsByMonthYear' : IDL.Func(
      [IDL.Nat8, IDL.Nat16],
      [IDL.Vec(ConsumptionItem)],
      ['query'],
    ),
  'getUniqueDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'resetData' : IDL.Func([], [], []),
  'saveEntry' : IDL.Func([SavedEntry], [], []),
  'searchItemsByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsumptionItem)],
      ['query'],
    ),
  'searchItemsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsumptionItem)],
      ['query'],
    ),
  'updateItemQuantity' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConsumptionItem = IDL.Record({
    'month' : IDL.Nat8,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'year' : IDL.Nat16,
    'itemCode' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
    'department' : IDL.Text,
  });
  const SavedRow = IDL.Record({
    'qty' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'itemCode' : IDL.Text,
    'department' : IDL.Text,
  });
  const SavedEntry = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'rows' : IDL.Vec(SavedRow),
    'savedAt' : IDL.Text,
    'savedBy' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func([ConsumptionItem], [], []),
    'bulkImport' : IDL.Func([IDL.Vec(ConsumptionItem)], [], []),
    'deleteAllEntries' : IDL.Func([], [], []),
    'deleteEntry' : IDL.Func([IDL.Text], [], []),
    'deleteItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(SavedEntry)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(ConsumptionItem)], ['query']),
    'getItemsByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsumptionItem)],
        ['query'],
      ),
    'getItemsByMonthYear' : IDL.Func(
        [IDL.Nat8, IDL.Nat16],
        [IDL.Vec(ConsumptionItem)],
        ['query'],
      ),
    'getUniqueDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'resetData' : IDL.Func([], [], []),
    'saveEntry' : IDL.Func([SavedEntry], [], []),
    'searchItemsByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsumptionItem)],
        ['query'],
      ),
    'searchItemsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsumptionItem)],
        ['query'],
      ),
    'updateItemQuantity' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };