/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsumptionItem {
  'month' : number,
  'name' : string,
  'unit' : string,
  'year' : number,
  'itemCode' : string,
  'notes' : string,
  'quantity' : number,
  'department' : string,
}
export interface _SERVICE {
  'addItem' : ActorMethod<[ConsumptionItem], undefined>,
  'bulkImport' : ActorMethod<[Array<ConsumptionItem>], undefined>,
  'deleteItem' : ActorMethod<[string, string], undefined>,
  'getAllItems' : ActorMethod<[], Array<ConsumptionItem>>,
  'getItemsByDepartment' : ActorMethod<[string], Array<ConsumptionItem>>,
  'getItemsByMonthYear' : ActorMethod<[number, number], Array<ConsumptionItem>>,
  'getUniqueDepartments' : ActorMethod<[], Array<string>>,
  'resetData' : ActorMethod<[], undefined>,
  'searchItemsByCode' : ActorMethod<[string], Array<ConsumptionItem>>,
  'searchItemsByName' : ActorMethod<[string], Array<ConsumptionItem>>,
  'updateItemQuantity' : ActorMethod<[string, string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];